version: '3'
services:
 mysql:
  image: mysql:8
  environment:
   MYSQL_DATABASE: 'cbr_data'
   MYSQL_USER: 'cbr-admin'
   MYSQL_PASSWORD: 'marsbars'
   MYSQL_ROOT_PASSWORD: 'root'
  ports:
   - "3306:3306"
  volumes:
   - mysql_volume:/var/lib/mysql
volumes:
 mysql_volume:

